services:
  app:
    image: allegrogh/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: postgres      
    # volumes:
    #   - ./app:/app
    command: make test
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

# volumes:
#   postgres_data:
