services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    environment:
      NODE_ENV: development
    command: make dev
