services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: allegrogh/devops-for-programmers-project-74
    environment:
      NODE_ENV: production
    command: make test

