services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: allegrogh/devops-for-programmers-project-74
    environment:
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy
    command: make test

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

volumes:
  postgres_data:
